version: '3'
name: 'url-shorter'

networks:
  main:
    driver: bridge

services:

  shorter:
    container_name: shorter
    build:
      context: .
      dockerfile: docker/shorter/Dockerfile
    restart: always
    depends_on:
      - kafka
      - redis
      - postgres
      - auth
      - qr
      - stats
    networks:
      - main
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    restart: always
    depends_on:
      - postgres
    networks:
      - main
    env_file:
      - .env

  qr:
    container_name: qr
    build:
      context: .
      dockerfile: docker/qr/Dockerfile
    restart: always
    networks:
      - main
    env_file:
      - .env

  stats:
    container_name: stats
    build:
      context: .
      dockerfile: docker/stats/Dockerfile
    restart: always
    depends_on:
      - kafka
    networks:
      - main
    env_file:
      - .env
    
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - main
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    networks:
      - main
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shorter
    volumes:
      - ./database:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - main
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - main

  
    
